// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADH51NqlLys5ggkp8i5BbDWZrVq5AZpnI',
    appId: '1:245055589810:web:bd601e6b1fc069733a68ab',
    messagingSenderId: '245055589810',
    projectId: 'workyo-d067d',
    authDomain: 'workyo-d067d.firebaseapp.com',
    storageBucket: 'workyo-d067d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqiuAsq9EPYchphRk7LT9JIAvZ1Igd4c',
    appId: '1:245055589810:android:86161136e23c8b1e3a68ab',
    messagingSenderId: '245055589810',
    projectId: 'workyo-d067d',
    storageBucket: 'workyo-d067d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASZn2vsC3Tk0PFtVA-wYt_Og6vyie101E',
    appId: '1:245055589810:ios:089ed4a05a006a663a68ab',
    messagingSenderId: '245055589810',
    projectId: 'workyo-d067d',
    storageBucket: 'workyo-d067d.firebasestorage.app',
    iosBundleId: 'com.example.workyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASZn2vsC3Tk0PFtVA-wYt_Og6vyie101E',
    appId: '1:245055589810:ios:089ed4a05a006a663a68ab',
    messagingSenderId: '245055589810',
    projectId: 'workyo-d067d',
    storageBucket: 'workyo-d067d.firebasestorage.app',
    iosBundleId: 'com.example.workyo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADH51NqlLys5ggkp8i5BbDWZrVq5AZpnI',
    appId: '1:245055589810:web:553c7517c4a136763a68ab',
    messagingSenderId: '245055589810',
    projectId: 'workyo-d067d',
    authDomain: 'workyo-d067d.firebaseapp.com',
    storageBucket: 'workyo-d067d.firebasestorage.app',
  );
}
